### ISSUE TITLE
BlurBehindView宽度match_Parent时左边有空隙

### ISSUE THREAD

**Issue by AllanGuoxiLee** [robinxdroid/BlurView#2]
![image](https://cloud.githubusercontent.com/assets/8438564/21560173/a11b62bc-ce95-11e6-8094-b3cc9fe69c28.png)
<net.robinx.lib.blurview.BlurBehindView
        android:id="@+id/blur_behind_view"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:layout_alignParentBottom="true">

**Comment by robinxdroid** [comment]
先使用BlurDrawable,我复查一下

**Comment by AllanGuoxiLee** [comment]
drawable的话，是右边有空隙。。。。

**Comment by robinxdroid** [comment]
fixd

**Comment by robinxdroid** [comment]
fixed
